version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=your_database_url
      - REDIS_URL=redis://redis:6379/0
      - FIREBASE_CONFIG=your_firebase_config
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"